name: 'Setup .NET and Build'
description: 'Sets up .NET environment, restores dependencies, and builds the project'
inputs:
  configuration:
    description: 'Build configuration'
    required: false
    default: 'Release'
  build-args:
    description: 'Additional build arguments'
    required: false
    default: '-p:ContinuousIntegrationBuild=True --no-restore'

runs:
  using: 'composite'
  steps:
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        global-json-file: global.json
        
    - name: Restore dependencies
      run: dotnet restore
      shell: pwsh
      
    - name: Build
      run: dotnet build --configuration ${{ inputs.configuration }} ${{ inputs.build-args }}
      shell: pwsh
