name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

defaults:
  run:
    shell: pwsh

jobs:
  build-and-test:
    name: build-and-test on ${{matrix.os}}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
    - uses: actions/checkout@v5
    - name: Setup .NET and Build
      uses: ./.github/actions/setup-dotnet-build
    - name: Test
      run: dotnet test --no-build --configuration Release --verbosity normal
      
  automerge:
    needs: [build-and-test]
    runs-on: ubuntu-latest
    
    permissions:
      pull-requests: write
      contents: write

    steps:
      - uses: fastify/github-action-merge-dependabot@v3.10.1  
